# Generated by Django 5.1.3 on 2025-11-26 20:23

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=255, verbose_name='Nombre del Parqueadero')),
                ('nit', models.CharField(blank=True, max_length=20, null=True)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parking_lot', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Parqueadero',
                'verbose_name_plural': 'Parqueaderos',
            },
        ),
        migrations.CreateModel(
            name='VehicleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('first_hour_rate', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('additional_hour_rate', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('is_monthly', models.BooleanField(default=False)),
                ('monthly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('parking_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='parking.parkinglot')),
            ],
            options={
                'verbose_name_plural': 'Vehicle Categories',
                'unique_together': {('parking_lot', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('tipo', models.CharField(choices=[('Ingreso', 'Ingreso'), ('Egreso', 'Egreso')], max_length=50)),
                ('monto', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('descripcion', models.TextField(blank=True)),
                ('dinero_inicial', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('dinero_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cuadre_realizado', models.BooleanField(default=False)),
                ('parking_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cajas', to='parking.parkinglot')),
            ],
            options={
                'unique_together': {('parking_lot', 'fecha', 'tipo')},
            },
        ),
        migrations.CreateModel(
            name='ParkingTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('placa', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('cascos', models.IntegerField(blank=True, null=True)),
                ('entry_time', models.DateTimeField(auto_now_add=True)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('barcode', models.ImageField(blank=True, upload_to='barcodes/')),
                ('monthly_expiry', models.DateTimeField(blank=True, null=True)),
                ('parking_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='parking.parkinglot')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.vehiclecategory')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('exit_time__isnull', True)), fields=('parking_lot', 'placa'), name='unique_active_plate_per_parking')],
            },
        ),
    ]
