# Generated by Django 5.1.1 on 2025-11-26 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingticket',
            name='es_mensualidad',
            field=models.BooleanField(default=False, verbose_name='Es Mensualidad'),
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre Completo')),
                ('documento', models.CharField(max_length=20, verbose_name='Documento de Identidad')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('placa', models.CharField(max_length=20, verbose_name='Placa del Vehículo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('parking_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='parking.parkinglot')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'unique_together': {('parking_lot', 'documento')},
            },
        ),
        migrations.AddField(
            model_name='parkingticket',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='parking.cliente'),
        ),
        migrations.CreateModel(
            name='Mensualidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Pago'), ('PAGADO', 'Pagado'), ('VENCIDO', 'Vencido'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Pago')),
                ('metodo_pago', models.CharField(blank=True, max_length=50, null=True, verbose_name='Método de Pago')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.vehiclecategory', verbose_name='Categoría')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensualidades', to='parking.cliente')),
                ('parking_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensualidades', to='parking.parkinglot')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensualidad', to='parking.parkingticket')),
            ],
            options={
                'verbose_name': 'Mensualidad',
                'verbose_name_plural': 'Mensualidades',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
