# Generated by Django 5.1.1 on 2025-11-26 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_parkingticket_es_mensualidad_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensualidad',
            name='metodo_pago',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Método de Pago (Legacy)'),
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Medio de Pago')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('icono', models.CharField(default='fa-money-bill-wave', max_length=50, verbose_name='Icono FontAwesome')),
                ('color', models.CharField(choices=[('primary', 'Azul'), ('success', 'Verde'), ('warning', 'Naranja'), ('danger', 'Rojo'), ('info', 'Cyan'), ('purple', 'Morado')], default='primary', max_length=20, verbose_name='Color')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('orden', models.IntegerField(default=0, verbose_name='Orden de visualización')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parking_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='parking.parkinglot')),
            ],
            options={
                'verbose_name': 'Medio de Pago',
                'verbose_name_plural': 'Medios de Pago',
                'ordering': ['orden', 'nombre'],
                'unique_together': {('parking_lot', 'nombre')},
            },
        ),
        migrations.AddField(
            model_name='mensualidad',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parking.paymentmethod', verbose_name='Medio de Pago'),
        ),
        migrations.AddField(
            model_name='parkingticket',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parking.paymentmethod', verbose_name='Medio de Pago'),
        ),
    ]
