# Generated by Django 5.1.1 on 2025-11-27 00:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_alter_mensualidad_metodo_pago_paymentmethod_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserParkingLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parking_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='parking.parkinglot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_lot_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asignación Usuario-Parqueadero',
                'verbose_name_plural': 'Asignaciones Usuario-Parqueadero',
                'unique_together': {('user', 'parking_lot')},
            },
        ),
    ]
