# Generated by Django 5.1.1 on 2025-11-27 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_userparkinglot'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinglot',
            name='annual_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio Anual'),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='last_payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Última Fecha de Pago'),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='monthly_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio Mensual'),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='payment_status',
            field=models.CharField(choices=[('PAGADO', 'Pagado'), ('PENDIENTE', 'Pendiente'), ('VENCIDO', 'Vencido')], default='PENDIENTE', max_length=20, verbose_name='Estado de Pago'),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='plan_type',
            field=models.CharField(choices=[('MENSUAL', 'Mensual'), ('ANUAL', 'Anual')], default='MENSUAL', max_length=10, verbose_name='Tipo de Plan'),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='subscription_end',
            field=models.DateField(blank=True, null=True, verbose_name='Fin de Suscripción'),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='subscription_start',
            field=models.DateField(blank=True, null=True, verbose_name='Inicio de Suscripción'),
        ),
    ]
