# Generated by Django 5.1.3 on 2025-11-27 01:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0005_parkinglot_annual_price_parkinglot_last_payment_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('payment_method', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia Bancaria'), ('TARJETA', 'Tarjeta de Crédito/Débito'), ('NEQUI', 'Nequi'), ('DAVIPLATA', 'Daviplata'), ('OTRO', 'Otro')], max_length=20, verbose_name='Método de Pago')),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Pago')),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Referencia')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='APROBADO', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription_start', models.DateField(verbose_name='Inicio de Suscripción')),
                ('subscription_end', models.DateField(verbose_name='Fin de Suscripción')),
                ('plan_type', models.CharField(max_length=10, verbose_name='Tipo de Plan')),
                ('parking_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_payments', to='parking.parkinglot', verbose_name='Parqueadero')),
                ('processed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payments', to=settings.AUTH_USER_MODEL, verbose_name='Procesado por')),
            ],
            options={
                'verbose_name': 'Pago de Suscripción',
                'verbose_name_plural': 'Pagos de Suscripción',
                'ordering': ['-payment_date'],
            },
        ),
    ]
